import { NextResponse } from "next/server";

// Define schema as raw JSON for Groq API
const analysisJsonSchema = {
    type: "object",
    properties: {
        score: { type: "number" },
        category_scores: {
            type: "object",
            properties: {
                impact: { type: "number" },
                brevity: { type: "number" },
                style: { type: "number" },
                structure: { type: "number" },
            },
            required: ["impact", "brevity", "style", "structure"],
        },
        keywords: {
            type: "object",
            properties: {
                found: { type: "array", items: { type: "string" } },
                missing: { type: "array", items: { type: "string" } },
            },
            required: ["found", "missing"],
        },
        feedback: { type: "array", items: { type: "string" } },
        red_flags: { type: "array", items: { type: "string" } },
        summary: { type: "string" },
    },
    required: ["score", "category_scores", "keywords", "feedback", "red_flags", "summary"],
    additionalProperties: false,
};

/**
 * Optimize resume data to reduce token usage
 */
function optimizeResumeData(data: any) {
    return {
        summary: data.personalInfo?.summary,
        jobTitle: data.personalInfo?.jobTitle,
        skills: Array.isArray(data.skills) ? data.skills.slice(0, 30) : [],
        experience: data.experience?.map((exp: any) => ({
            role: exp.title,
            company: exp.company,
            highlights: exp.description?.substring(0, 300) // Truncate
        })).slice(0, 5),
        education: data.education?.map((edu: any) => ({
            degree: edu.degree,
            field: edu.field,
            school: edu.school
        })).slice(0, 2)
    };
}

export async function POST(req: Request) {
    try {
        const apiKey = process.env.GROQ_API_KEY;

        if (!apiKey) {
            console.error("❌ GROQ_API_KEY is not set");
            return NextResponse.json(
                {
                    error: "Invalid API Key",
                    details: "GROQ_API_KEY environment variable is not loaded.",
                    solution: "Check .env.local configuration."
                },
                { status: 500 }
            );
        }

        console.log("✅ Using Groq API via Fetch");

        const { resumeData, jobDescription } = await req.json();

        // Optimize payload
        const optimizedResume = optimizeResumeData(resumeData);

        const prompt = `
        Act as a strict, professional Applicant Tracking System (ATS) and expert Resume Coach.
        1. Analyze the RESUME SUMMARY below.
        2. Check for impact, clarity, keywords, and red flags.
        ${jobDescription ? '3. Compare relevance to the JOB DESCRIPTION.' : ''}

        RESUME SUMMARY:
        ${JSON.stringify(optimizedResume, null, 2)}

        ${jobDescription ? `JOB DESCRIPTION (Analyze against this):\n${jobDescription.slice(0, 1500)}` : ''}

        Call the 'analyze_resume' tool with a detailed analysis.
        `;

        try {
            const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${apiKey}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    model: "llama-3.3-70b-versatile",
                    messages: [{ role: 'user', content: prompt }],
                    tools: [
                        {
                            type: "function",
                            function: {
                                name: "analyze_resume",
                                description: "Submit the analysis of the resume",
                                parameters: analysisJsonSchema
                            }
                        }
                    ],
                    tool_choice: "required",
                    temperature: 0.3
                })
            });

            if (!response.ok) {
                const errBody = await response.text();
                throw new Error(`Groq API Error: ${response.status} - ${errBody}`);
            }

            const data = await response.json();
            const toolCall = data.choices[0]?.message?.tool_calls?.[0];

            if (!toolCall) {
                throw new Error("No analysis generated by AI. Model did not call the tool.");
            }

            // Parse the arguments (JSON string)
            const analysisResult = JSON.parse(toolCall.function.arguments);

            return NextResponse.json(analysisResult);

        } catch (apiError: any) {
            console.error("Groq API Call Failed:", apiError);
            throw apiError; // Re-throw to be caught by outer catch
        }

    } catch (error: any) {
        console.error("ATS Analysis failed:", error);

        return NextResponse.json(
            {
                error: error.message || "Analysis failed",
                details: "AI Service error. Check API configuration or logs.",
            },
            { status: 500 }
        );
    }
}
